### ISSUE TITLE
Can't locate IPC/Run3.pm in @INC?

### ISSUE THREAD

**Issue by Kevinf63** [azlm8t/tv_grab_az_sdjson_sqlite#2]
If I run the grabber in any shape or form, if even just for --help I get the following error attached.

![image](https://user-images.githubusercontent.com/3584482/61084952-04a34700-a427-11e9-903d-a915a1078d3e.png)

AFAIK, I've copied the grabber into the /usr/bin and followed your guidelines here for additional packages:
https://github.com/azlm8t/tv_grab_az_sdjson_sqlite#extra-packages-required

I hope its something silly on my end! :)

**Comment by azlm8t** [comment]
Sorry for the long delay in replying (holidays).

I believe the package you require on Debian systems for IPC::Run3 is libipc-run3-perl. I'll add it to the list of dependencies. It's probable that on my system that the dependency was installed via some other program.

If there are other missing one then you might be able to find them via "apt search ABC:DEF" (assuming it says missing ABC:DEF module).

Hope this helps.

**Comment by Kevinf63** [comment]
Absolute gent. That sorted me out and thank you for taking the time out to respond! Just for note, I ran into this problem on a Ubuntu Server VM, which is obviously more stripped back than a regular Ubuntu distro, a la Debian.
