### ISSUE TITLE
db do failed: Cannot add or update a child row

### ISSUE THREAD

**Issue by pmeeke** [azlm8t/tv_grab_az_sdjson_sqlite#3]
I seem to be getting an error if you can help me. 

`DBD::mysql::db do failed: Cannot add or update a child row: a foreign key constraint fails (`imdb`.`imdb_ratings`, CONSTRAINT `imdb_ratings_ibfk_1` FOREIGN KEY (`tconst`) REFERENCES `imdb_title` (`tconst`) ON DELETE CASCADE) at /usr/bin/tv_grab_az_sdjson_sqlite line 7624.`

**Comment by azlm8t** [comment]
Sorry for the long delay in replying (holidays).

Hm. I haven't seen that error.  Unfortunately, SQL hasn't given enough info on the exact row that failed.

It is inserting the ratings and cross-referencing it to the title details. So, we'd expect that a rating always refers back to a title (can't rate something that doesn't exist!)

Perhaps one of the files failed to download correctly? Or it just happened that the download occurred when the download of the title file was for yesterday but the ratings download just happened to update (on imdb server) while you were downloading the title file so ratings were for today and so gave a rating. for a programme not in the title file.

Does the error repeat all the time? If so, perhaps alter your crontab to be later (to avoid potential of imdb server updating files while we are downloading).
