### ISSUE TITLE
Not an issue - just a query.

### ISSUE THREAD

**Issue by elsmandino** [azlm8t/tv_grab_az_sdjson_sqlite#4]
Hi there,

I am in the process of upgrading my system from TVH 4.2 to 4.3.

Will the grabber work equally well with 4.3 or are there any differences that I need to be aware of?

**Comment by azlm8t** [comment]
It will work fine with no changes needed.

The main difference you will notice is that 4.3 will pass artwork through to clients, such as newer versions of Kodi. This will only happen for new recordings.

**Comment by elsmandino** [comment]
Thanks very much for that - really appreciate that.
